### PR TITLE
[JENKINS-42959] support Ed25519 keys

### PR DESCRIPTION
**Pull request by mc1arke**
Trilead currently silently ignores any Ed25519 public key entries found in known_hosts, doesn't support them for identifying a remote host, and can't use Ed25519 keys in user public key authentication. This change provides this support, as well as various other commits to allow some abstraction and extension of provision of key types (as shared with #12)

### CODE REVIEW

**Comment by mc1arke** [comment]
Requires a release of str4d/ed255219-java v0.2 to build properly, and I'd like to support encrypted openssh key parsing

**Comment by paladox** [comment]
0.2.0 has been released now. https://search.maven.org/#search%7Cga%7C1%7Cnet.i2p.crypto

**Comment by paladox** [comment]
Is this still a wip? If not can this be merged please?

**Comment by mc1arke** [comment]
I'd like to be able to work out the decryption of encrypted open-ssh keys which, whilst not critical for this branch, does cause a level of security functionality to be missed (you'd only be able to use un-encrypted private keys for Ed25519).

On a slightly related note, newer format open-ssh keys can also be used for RSA, DSA and ECDSA keys so it would be nice to include support for them too which may require a slight API change (possibly under another pull request once this one gets merged) and some abstraction of the core open-ssh key parsing.

I'd also ideally like another review from another developer, preferably with some knowledge of ssh and/or Trilead before merging this.

**Comment by paladox** [comment]
seems to fail with

Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.148 sec <<< FAILURE!
testParsePrivateKey(com.trilead.ssh2.signature.ED25519KeyAlgorithmTest)  Time elapsed: 0.013 sec  <<< ERROR!
java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1582)
	at org.apache.commons.io.IOUtils.toCharArray(IOUtils.java:585)
	at com.trilead.ssh2.signature.ED25519KeyAlgorithmTest.testParsePrivateKey(ED25519KeyAlgorithmTest.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running com.trilead.ssh2.signature.RSAKeyAlgorithmTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.363 sec

**Comment by paladox** [comment]
this should be ready to merge.

**Comment by bguerout** [comment]
Is this supposed to fix this https://issues.jenkins.io/browse/JENKINS-30319 ?

**Comment by paladox** [comment]
Yup, i think so.

**Comment by f1mishutka** [comment]
Any change for this to be merged?

It is 2022 and Jenkins does not support ED25519 keys yet... :(

**Pull request merged**
