### PR TITLE
test: which test is stuck

### PR DESCRIPTION
**Pull request by kuisathaverat**
this job takes 4 hours on CI, locally it takes less than 5 min so something does not work on the CI as expected

### CODE REVIEW

**Comment by kuisathaverat** [comment]
I think is the random device Bug

https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4820090
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6521844

https://stackoverflow.com/questions/137212/how-to-deal-with-a-slow-securerandom-generator

**Comment by kuisathaverat** [comment]
confirmed the 4hours block in a test was because the `SecureRandom.getInstanceStrong();`

cc @jvz

**Comment by jvz** [comment]
Should we use some sort of `SecureRandomProvider` interface to abstract that out? Use of the "slow" initializing random generator is probably correct behavior in production, but unnecessary in tests (I usually use a static seed for random number generators in unit tests).

**Comment by kuisathaverat** [comment]
> Should we use some sort of `SecureRandomProvider` interface to abstract that out? Use of the "slow" initializing random generator is probably correct behavior in production, but unnecessary in tests (I usually use a static seed for random number generators in unit tests).

SecureRandom instance uses the default algorithm that is fast so I think is fine, we use it on other tests.

**Pull request merged**
