### PR TITLE
[FIXED JENKINS-33021] Add support for SHA256 and SHA512 HMAC algorithms

### PR DESCRIPTION
**Pull request by mc1arke**
An alternative to #9 and #7  that reduces the number of classes under change and doesn't break binary compatibility.

### CODE REVIEW

**Comment by mc1arke** [comment]
@paladox I've run this against a local RHEL instance with SSHD configured to only allow SHA-256 and then reconfigured to only allow SHA-512 MACs and this connected OK. Are you able to build this and run whatever testing you'd been doing for your implementation to check this works for you?

**Comment by paladox** [comment]
I can test this now.

**Comment by paladox** [comment]
@mc1arke i have tested now but i get this

ERROR: Connection terminated
java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2624)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3099)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:853)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:349)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:59)
Caused: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:73)

**Comment by paladox** [comment]
It connects but then disconnects

[04/04/17 21:52:08] [SSH] SSH host key matches key seen previously for this host. Connection will be allowed.
[04/04/17 21:52:08] [SSH] Authentication successful.
[04/04/17 21:52:08] [SSH] The remote users environment is:
BASH=/bin/bash
BASHOPTS=cmdhist:complete_fullquote:extquote:force_fignore:hostcomplete:interactive_comments:progcomp:promptvars:sourcepath
BASH_ALIASES=()
BASH_ARGC=()
BASH_ARGV=()
BASH_CMDS=()
BASH_EXECUTION_STRING=set
BASH_LINENO=()
BASH_SOURCE=()
BASH_VERSINFO=([0]="4" [1]="3" [2]="30" [3]="1" [4]="release" [5]="x86_64-pc-linux-gnu")
BASH_VERSION='4.3.30(1)-release'
DIRSTACK=()
EUID=15041
GROUPS=()
HOME=/home/test-jenkins
HOSTNAME=jenkins-slave-01
HOSTTYPE=x86_64
IFS=$' \t\n'
LANG=en_US.UTF-8
LOGNAME=test-jenkins
MACHTYPE=x86_64-pc-linux-gnu
MAIL=/var/mail/test-jenkins
OPTERR=1
OPTIND=1
OSTYPE=linux-gnu
PATH=/usr/local/bin:/usr/bin:/bin:/usr/games
PIPESTATUS=([0]="0")
PPID=23427
PS4='+ '
PWD=/home/test-jenkins
SHELL=/bin/bash
SHELLOPTS=braceexpand:hashall:interactive-comments
SHLVL=1
SSH_CLIENT='10.68.20.204 54490 22'
SSH_CONNECTION='10.68.20.204 54490 10.68.22.0 22'
TERM=dumb
UID=15041
USER=test-jenkins
_=']'
[04/04/17 21:52:08] [SSH] Checking java version of java
[04/04/17 21:52:08] [SSH] java -version returned 1.7.0_121.
[04/04/17 21:52:08] [SSH] Starting sftp client.
[04/04/17 21:52:08] [SSH] Copying latest slave.jar...
[04/04/17 21:52:08] [SSH] Copied 719,269 bytes.
Expanded the channel window size to 4MB
[04/04/17 21:52:08] [SSH] Starting slave process: cd "/var/lib/jenkins" && java  -jar slave.jar
<===[JENKINS REMOTING CAPACITY]===>channel started
Slave JVM has not reported exit code. Is it still running?
[04/04/17 21:52:13] Launch failed - cleaning up connection
[04/04/17 21:52:13] [SSH] Connection closed.
ERROR: Connection terminated
java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2624)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3099)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:853)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:349)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:59)
Caused: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:73)
[04/04/17 21:53:31] [SSH] Opening SSH connection to jenkins-slave-01:22.
[04/04/17 21:53:31] [SSH] SSH host key matches key seen previously for this host. Connection will be allowed.
[04/04/17 21:53:32] [SSH] Authentication successful.
[04/04/17 21:53:32] [SSH] The remote users environment is:
BASH=/bin/bash
BASHOPTS=cmdhist:complete_fullquote:extquote:force_fignore:hostcomplete:interactive_comments:progcomp:promptvars:sourcepath
BASH_ALIASES=()
BASH_ARGC=()
BASH_ARGV=()
BASH_CMDS=()
BASH_EXECUTION_STRING=set
BASH_LINENO=()
BASH_SOURCE=()
BASH_VERSINFO=([0]="4" [1]="3" [2]="30" [3]="1" [4]="release" [5]="x86_64-pc-linux-gnu")
BASH_VERSION='4.3.30(1)-release'
DIRSTACK=()
EUID=15041
GROUPS=()
HOME=/home/test-jenkins
HOSTNAME=jenkins-slave-01
HOSTTYPE=x86_64
IFS=$' \t\n'
LANG=en_US.UTF-8
LOGNAME=test-jenkins
MACHTYPE=x86_64-pc-linux-gnu
MAIL=/var/mail/test-jenkins
OPTERR=1
OPTIND=1
OSTYPE=linux-gnu
PATH=/usr/local/bin:/usr/bin:/bin:/usr/games
PIPESTATUS=([0]="0")
PPID=23489
PS4='+ '
PWD=/home/test-jenkins
SHELL=/bin/bash
SHELLOPTS=braceexpand:hashall:interactive-comments
SHLVL=1
SSH_CLIENT='10.68.20.204 54538 22'
SSH_CONNECTION='10.68.20.204 54538 10.68.22.0 22'
TERM=dumb
UID=15041
USER=test-jenkins
_=']'
[04/04/17 21:53:32] [SSH] Checking java version of java
[04/04/17 21:53:32] [SSH] java -version returned 1.7.0_121.
[04/04/17 21:53:32] [SSH] Starting sftp client.
[04/04/17 21:53:32] [SSH] Copying latest slave.jar...
[04/04/17 21:53:32] [SSH] Copied 719,269 bytes.
Expanded the channel window size to 4MB
[04/04/17 21:53:32] [SSH] Starting slave process: cd "/var/lib/jenkins" && java  -jar slave.jar
<===[JENKINS REMOTING CAPACITY]===>channel started
Slave JVM has not reported exit code. Is it still running?
[04/04/17 21:53:36] Launch failed - cleaning up connection
[04/04/17 21:53:36] [SSH] Connection closed.
ERROR: Connection terminated
java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2624)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3099)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:853)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:349)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:59)
Caused: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:73)

**Comment by mc1arke** [comment]
Interestingly it looks like it allows the SCP step but then fails at some point after that, so should have gone through a full MAC cycle during the initial authentication. I've only run this change through a modified version of the RoundTripTest in this project rather than through a downstream dependent project so it may be that one of the steps in the slave launch process runs a command that doesn't use my new code properly. I'll turn on full logging in my Trilead build, locally bundle the library in the ssh-slaves plugin and try and replicate your issue to see what it tells me.

Are you able to confirm the configuration of your ssh host: specifically any particular MAC or key format/size restrictions in case this plays a part in this issue?

**Comment by paladox** [comment]
Hi, the mac i am using on the server it's trying to connect to is

MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com

and nope no particular key format size restrictions i think.

**Comment by paladox** [comment]
I retested with https://github.com/jenkinsci/trilead-ssh2/issues/9 now and it seems i am now having the problem with that too. It seems that the difference is i git pulled jenkins for any updates upstream before building your change. So looks like a bug in jenkins.

**Comment by paladox** [comment]
though it could be that it caches it so it may be with this patch here.

**Comment by paladox** [comment]
Ah, it's because they use switched to java 8. So i had to update java to 8 on the slaves.

**Comment by paladox** [comment]
This works now. As soon as switching to 1.8 it works :)

**Comment by paladox** [comment]
can this be merged please?

**Comment by mc1arke** [comment]
@paladox thanks for the confirmation.

As with my other pull requests for this library, I'd ideally like a second review; preferably from someone who understands SSH or Trilead. I'll put the usual request for @jenkinsci/code-reviewers to take a look, but anyone else looking at this (@elisedlund?) is welcome to chip in with comments on the quality of the code or the functionality of the change.

**Comment by paladox** [comment]
How long would we wait for a review? As looking at other changes that call for a review none have reviewed those.

**Comment by mc1arke** [comment]
I'll ask on the Jenkins IRC channel if anyone is prepared to look, but will give the change at least 24 hours for review before I merge it.

Where is it you're using the library from? I'm presuming it's ssh-slaves-plugin given your test you attempted?

**Comment by paladox** [comment]
Yep its the ssh-slave plugin but i manually built trilead-ssh2 with your change then i use the -SNAPSHOT version in jenkins and built jenkins too with the trilead-ssh2 change.

**Comment by paladox** [comment]
Should we wait 24 hours for your other changes too before merging those? And should we make a new release too so it can be included in jenkins?

Thankyou so much for working on this. This will allow us to disable sha1 on the jenkins server on wikimedia. As we currently have to enable backwords compat for sha1.

**Comment by paladox** [comment]
@mc1arke i think this got reviewed by someone on irc.

**Comment by hashar** [comment]
For wikimedia setup, you can get a list of offered MACs / Ciphers via: `ssh -vv bastion.wmflabs.org`.

The sshd_config is publicly available and has:
```
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_dsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key

Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr

MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
```

In order to have Jenkins to connect we have to drop our specific MACs list. According to sshd_config(5) the default would thus be:
```
                   umac-64-etm@openssh.com,umac-128-etm@openssh.com,
                   hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,
                   umac-64@openssh.com,umac-128@openssh.com,
                   hmac-sha2-256,hmac-sha2-512
```

**Comment by paladox** [comment]
@mc1arke it has been 24 hours now :)

**Comment by paladox** [comment]
bump.

**Comment by marklagendijk** [comment]
@mc1arke, @paladox will this be released as soon as it is merged in?
At my company we are waiting for this. As soon as this is released we can start using slaves.

**Comment by oleg-nenashev** [comment]
I will try to review it within several days if it does not get merged before that

**Comment by mc1arke** [comment]
I'm about to merge my outstanding requests, but then want to make one further change before I do a release, so it's likely to be another 24 hours before these changes are built and released.

Even once I release these, none of Jenkins will be using the new version of Trilead: I'll have to raise a change against Jenkins core to update their bundled version, and may raise a change against SSH slaves to bundle Trilead directly so users don't have to wait until they move to the latest Core version.

**Comment by paladox** [comment]
@mc1arke probably want to rebase this.

**Comment by paladox** [comment]
@marklagendijk hi, this change will also fix wikimedia's problem too :)

**Comment by paladox** [comment]
thank you :)

**Comment by paladox** [comment]
@mc1arke hi, i pulled the master branch. When i test again it fails with a timeout error

[04/11/17 10:56:56] [SSH] Opening SSH connection to jenkins-slave-01:22.
Connection timed out (Connection timed out)
SSH Connection failed with IOException: "Connection timed out (Connection timed out)".
java.io.IOException: There was a problem while connecting to jenkins-slave-01:22
	at com.trilead.ssh2.Connection.connect(Connection.java:818)
	at com.trilead.ssh2.Connection.connect(Connection.java:687)
	at com.trilead.ssh2.Connection.connect(Connection.java:601)
	at hudson.plugins.sshslaves.SSHLauncher.openConnection(SSHLauncher.java:1265)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:790)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:785)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.trilead.ssh2.transport.TransportManager.establishConnection(TransportManager.java:354)
	at com.trilead.ssh2.transport.TransportManager.initialize(TransportManager.java:467)
	at com.trilead.ssh2.Connection.connect(Connection.java:758)
	... 9 more
[04/11/17 10:59:06] Launch failed - cleaning up connection
[04/11/17 10:59:06] [SSH] Connection closed.


which is strange. Maybe the other pulls broke it?

**Comment by paladox** [comment]
This patch is the cause. No other pull causing the problem. I tested by going back before all the pulls were merge. I then cherry picked this. It seems the rebase you did broke something.

**Comment by paladox** [comment]
Oh never mind. It seems somehow jenkins-slave-01 carn't be reached from gerrit-test which is strange.

**Comment by marklagendijk** [comment]
@mc1arke, @paladox thanks for the great work!
Now that this has been merged and released: what do I need to do to start using this?
When will this be available in the released Jenkins version? Is it easy to manually start using it in the mean time?

**Comment by paladox** [comment]
@marklagendijk hi, @mc1arke is currently trying to see if he can get trilead-ssh2 to be updated in the ssh slaves plugin without an upgrade to jenkins. If that dosen't work trilead-ssh2 will be updated in jenkins core and will require a jenkins update.

**Comment by marklagendijk** [comment]
Having it updated in the plugin would indeed be nice. I suppose that for many organizations it is not so trivial to update Jenkins to the latest version.
What would be the best way to follow the progress of this?

**Comment by paladox** [comment]
@marklagendijk hi, you can follow progress here https://issues.jenkins-ci.org/browse/JENKINS-33021

**Pull request merged**
