### PR TITLE
[JENKINS-62311] Add support for RFC 8332

### PR DESCRIPTION
**Pull request by jvz**
This adds two more key algorithms:
- rsa-sha2-256
- rsa-sha2-512

@jeffret-b @daniel-beck @Wadeck @kuisathaverat 

https://issues.jenkins-ci.org/browse/JENKINS-62311
https://tools.ietf.org/html/rfc8332

### CODE REVIEW

**Comment by kuisathaverat** [comment]
Could you add some tests for the new algorithms like https://github.com/jenkinsci/trilead-ssh2/blob/master/test/com/trilead/ssh2/signature/RSAKeyAlgorithmTest.java?

**Comment by jvz** [comment]
That last test failure is weird. Works on my machine!

**Comment by jvz** [comment]
@kuisathaverat ping? The latest version of OpenSSH requires this patch now.

**Comment by kuisathaverat** [comment]
@jvz I worried about the test does not pass the CI

**Comment by jvz** [comment]
Let me try rerunning them.

**Comment by jvz** [comment]
Sweet, it worked that time. Previous failures might've been infra-related.

**Pull request merged**
