### PR TITLE
Trilead ssh2 fix big integer removes leading zero

### PR DESCRIPTION
**Pull request by mpet**
See [JENKINS-72715](https://issues.jenkins.io/browse/JENKINS-72715).

### CODE REVIEW

**Comment by mpet** [comment]
@kuisathaverat  if you have any questions I have added info in the JIRA. Is it possible to have a beta I can use and send to tester for verification that would be great!

**Comment by kuisathaverat** [comment]
incrementals are enabled so you have binaries at  https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/trilead-ssh2/build-217-jenkins-305.vd76f25b_438b_b_/

**Review by kuisathaverat — APPROVED** [review]

**Comment by kuisathaverat** [comment]
As soon as you confirm there is nothing more to do here, we can merge it.

**Comment by mpet** [comment]
@kuisathaverat  customer verified and it works!

**Comment by kuisathaverat** [comment]
released at https://github.com/jenkinsci/trilead-ssh2/releases/tag/build-217-jenkins-293.v56de4d4d3515

**Pull request merged**
