### PR TITLE
[Test] Revert "Resolve several possible infinite hangings because of wait()"

### PR DESCRIPTION
**Pull request by kuisathaverat**
Reverts jenkinsci/trilead-ssh2#44

I think it causes https://issues.jenkins-ci.org/browse/JENKINS-63790

### CODE REVIEW

**Review by jvz — APPROVED** [review]

**Comment by kuisathaverat** [comment]
@Elisedlund-ericsson we have hit an issue and it seems related to this change, I cannot explain how it affects some systems but it does. Probably I have to revert the change

**Comment by Elisedlund-ericsson** [comment]
@kuisathaverat I find it very unlikely to cause: https://issues.jenkins-ci.org/browse/JENKINS-63790 is there some addtional logs? 
the only thing would be if any of these request takes longer than 2min (which I set as a generous worst worst case) 
then the fix could just be the increase this default timeout to something larger 10-20min which would be far better than infinite hangings.

**Comment by kuisathaverat** [comment]
I do not have an explanation too, but with a VM on GCP Java 8 I've seen timeouts after 6 seconds with this change, removing the change the issue disappear. Marks said that replicates the issue with VMs and Java 11, and also with the change removed the issue disappears. It is really weird.

**Comment by kuisathaverat** [comment]
@Elisedlund-ericsson sorry for the noise it is not related to this change, is something related to the interchange of the SSH2_MSG_NEWKEYS message, so should be related to the new encryptions supported changes.

**Pull request closed without merging**
